### ISSUE TITLE
IndentingListMorph>>unhighlight sets text to black

### ISSUE THREAD

**Issue by gurehamu** [jvuletich/Cuis#6]
When browsing directories in File List, the tree view pane changes the text color to black after unselecting a directory.  When using dark pane background, the text becomes unreadable on deselection.  It looks like IndentingListMorph>>unhighlight is the origin of this setting.

Possible solution?

IndentingListItemMorph>>unhighlight

```
complexContents highlightingColor ifNotNil: [self color: Theme current text].
self redrawNeeded
```

**Comment by jvuletich** [comment]
You're right! Thank you. I integrated your fix.
